/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user".
 */
export interface User {
    id: string;
    email?: string;
    resetPasswordToken?: string;
    resetPasswordExpiration?: string;
    loginAttempts?: number;
    lockUntil?: string;
    fullName: string;
    createdAt: string;
    updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
    id: string;
    url?: string;
    filename?: string;
    mimeType?: string;
    filesize?: number;
    image: string | Media;
    name: string;
    playerName: string;
    type?: 'Single cards' | 'Boxes';
    sportType: string;
    year: string;
    price: number;
    leagueTeam: 'NBA' | 'NFL' | 'MLB' | 'NHL' | 'Random team';
    seller: string | User;
    specialFeature: string;
    brand: string;
    gradeBy: string;
    rating: number;
    createdAt: string;
    updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: string;
    url?: string;
    filename?: string;
    mimeType?: string;
    filesize?: number;
    alt?: string;
    createdAt: string;
    updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourite-product".
 */
export interface FavouriteProduct {
    id: string;
    user: string | User;
    product: string | Product;
    createdAt: string;
    updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bidding".
 */
export interface Bidding {
    id: string;
    product: string | Product;
    user: string | User;
    price: number;
    createdAt: string;
    updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-break".
 */
export interface LiveBreak {
    id: string;
    url?: string;
    filename?: string;
    mimeType?: string;
    filesize?: number;
    image: string | Media;
    name: string;
    sportType: string;
    year: string;
    price: number;
    leagueTeam?: 'NBA' | 'NFL' | 'MLB' | 'NHL' | 'Random team';
    seller: string | User;
    specialFeature: string;
    brand: string;
    gradeBy: string;
    rating: number;
    createdAt: string;
    updatedAt: string;
}
